name: lyrics_parser
description: >-
  .lrc file parser and lyrics tracker.
version: 1.0.0-nullsafety
homepage: https://github.com/fusee-code-lab/lyrics_parser

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
 path: ^1.8.0-nullsafety.3
 characters: ^1.1.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.19
